site_name: Stanford CS269I Course Notes
theme:
  name: material
  nav_title: Custom Sidebar Title
  palette:
    scheme: default
  features:
    - navigation.instant
    - navigation.sections

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.superfences
  - attr_list
  - md_in_html

extra_javascript:
  - https://cdn.jsdelivr.net/npm/katex@0.16.10/dist/katex.min.js
  - https://cdn.jsdelivr.net/npm/katex@0.16.10/dist/contrib/auto-render.min.js
  - javascript/katex-init.js

extra_css:
  - https://cdn.jsdelivr.net/npm/katex@0.16.10/dist/katex.min.css
  - stylesheets/extra.css

nav:
  - One-Sided Matching and Serial Dictatorship: lecture-1.md
  - Stable Two-Sided Matchings: lecture-2.md
  - Online Learning and Regret Minimization: lecture-3.md
  - Top Trading Cycles: lecture-3-2023.md
  - Equilibria in Games: lecture-4.md
  - P2P File-sharing Dilemma: lecture-5.md
  - Market Equilibrium: lecture-6.md
  - Market Failures: lecture-7.md
  - Auctions: lecture-8.md
  - Prediction Markets and Information Cascades: lecture-9.md
  - Mid-Quarter Review Party: lecture-9.5.md
  - How to Train an AI That Doesn't Lie: guest-lecture-eric-neyman.md
  - Scoring Rules: lecture-10.md
  - Incentives in Sponsored Search Auctions: guest-lecture-kshipra-bhawalkar.md
  - Proof-of-Work Blockchains: lecture-11.md