site_name: Stanford CS269I Course Notes
theme:
  name: material
  palette:
    scheme: default
  features:
    - navigation.instant
    - navigation.sections

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.superfences
  - attr_list
  - md_in_html

extra_javascript:
  - https://cdn.jsdelivr.net/npm/katex@0.16.10/dist/katex.min.js
  - https://cdn.jsdelivr.net/npm/katex@0.16.10/dist/contrib/auto-render.min.js
  - javascript/katex-init.js

extra_css:
  - https://cdn.jsdelivr.net/npm/katex@0.16.10/dist/katex.min.css
  - stylesheets/extra.css

nav:
  - Welcome: index.md
  - One-Sided Matching and Serial Dictatorship: lecture1.md
  - Stable Two-Sided Matchings: lecture2.md
  - Online Learning and Regret Minimization: lecture3.md
  - Top Trading Cycles: lecture3b.md
  - Equilibria in Games: lecture4.md